### ISSUE TITLE
Build  Falied

### ISSUE THREAD

**Issue by darionyaphet** [linkedin/databus#30]
Building databus on mac os  
jvm : 
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)

gradle 1.10 

Exception Stack as follow ~  
10:13:31.991 [ERROR] [org.gradle.BuildExceptionReporter] 
10:13:31.992 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
10:13:31.992 [ERROR] [org.gradle.BuildExceptionReporter] 
10:13:31.993 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
10:13:31.993 [ERROR] [org.gradle.BuildExceptionReporter] Could not resolve all dependencies for configuration ':databus2-relay:databus2-event-producer-mock:compile'.
10:13:31.994 [ERROR] [org.gradle.BuildExceptionReporter] > Could not download artifact 'com.oracle:ojdbc6:11.2.0.2.0:ojdbc6.jar'
10:13:31.994 [ERROR] [org.gradle.BuildExceptionReporter]    > Artifact 'com.oracle:ojdbc6:11.2.0.2.0:ojdbc6.jar' not found.
10:13:31.995 [ERROR] [org.gradle.BuildExceptionReporter] 
10:13:31.996 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
10:13:31.998 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':databus2-relay:databus2-event-producer-mock:compile'.
10:13:31.999 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingArtifactDependencyResolver.wrapException(ErrorHandlingArtifactDependencyResolver.java:57)
10:13:31.999 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingArtifactDependencyResolver.access$000(ErrorHandlingArtifactDependencyResolver.java:34)
10:13:32.000 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingArtifactDependencyResolver$ErrorHandlingResolvedConfiguration.getFiles(ErrorHandlingArtifactDependencyResolver.java:186)
10:13:32.000 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:467)
10:13:32.000 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:202)
10:13:32.001 [ERROR] [org.gradle.BuildExceptionReporter]

**Comment by psrinivasulu** [comment]
@darionyaphet Were you able to resolve this issue? Please try to use JDK 1.6 for building and see if it works.
