### ISSUE TITLE
Error during build with gradle 1.11

### ISSUE THREAD

**Issue by bobmercer** [linkedin/databus#36]
Hello,

I have an issue during my build process. I am using gradle v1.11 and it seems that the build is Failed due to javadoc compilation. 

![screenshot](https://cloud.githubusercontent.com/assets/4498840/3721707/0e752f66-1663-11e4-9cba-41f8cecc7ec7.png)

I guess I missed something but cannot find out what's going wrong... 
Could you help me please?
Thanks in advance,

Damien

**Comment by psrinivasulu** [comment]
Hi @bobmercer,  Glad you were able to resolve this issue. Thanks,
