### ISSUE TITLE
Can Databus use the  Slave Relay Log instead of the Bin Log from Master

### ISSUE THREAD

**Issue by synckey** [linkedin/databus#45]
I wonder if I can use the Slave Relay Log to subscribe the change events instead of using the Bin Log. 
For this approach can  reduce io stress from the master. If I can,how to config Databus?
Thanks
Andy Wang

**Comment by psrinivasulu** [comment]
Hi @synckey 

Sorry this scenario is not tested. Not sure whether this will work at all.

Thanks,
Srini.
