### ISSUE TITLE
How to generate Mysql table schema?

### ISSUE THREAD

**Issue by synckey** [linkedin/databus#46]
Dear all
I want to use databus with Mysql.But  the `com.linkedin.databus.util.InteractiveSchemaGenerator`  tool and related classes can only generate Oracle DB Table schemas. It seems that there is not a tool for Mysql to generate schemas.Is there any alternative ways for me to do with mysql?
Thanks.

**Comment by jagadeesh-huliyar** [comment]
You could use https://github.com/Flipkart/aesop/tree/master/avro-schema-generator to generate avro schema for MySql

**Comment by psrinivasulu** [comment]
Thanks @jagadeesh-huliyar. Do you use databus for Mysql in your organization? Are you using this avro schema generator with respect to databus for Mysql?

Hi @hopecheng - Hope your question is answered. 

Thanks,
Srini.
