### ISSUE TITLE
Does anyone meet this assert error ?

### ISSUE THREAD

**Issue by hopecheng** [linkedin/databus#47]
I register one table and after running some time, I find the error in logs:
java.lang.AssertionError
     29     at com.linkedin.databus.core.DbusEventBuffer.startEvents(DbusEventBuffer.java:1671)
     30     at com.linkedin.databus2.producers.OpenReplicatorEventProducer$EventProducerThread.addTxnToBuffer(OpenReplicatorEventProducer.java:620)
     31     at com.linkedin.databus2.producers.OpenReplicatorEventProducer$EventProducerThread.onEndTransaction(OpenReplicatorEventProducer.java:566)
     32     at com.linkedin.databus2.producers.ORListener.endXtion(ORListener.java:360)
     33     at com.linkedin.databus2.producers.ORListener.onEvents(ORListener.java:206)
     34     at com.google.code.or.binlog.impl.AbstractBinlogParser$Context.onEvents(AbstractBinlogParser.java:313)
     35     at com.google.code.or.binlog.impl.parser.QueryEventParser.parse(QueryEventParser.java:76)
     36     at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:129)
     37     at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:244)
     38     at java.lang.Thread.run(Thread.java:636)

What does this error mean? After this error, I can't catch any changes of MySQL.

**Comment by psrinivasulu** [comment]
Hi @hopecheng , Performing an end Transaction on a finally block on end transaction might result in loss of events. Which we would want to avoid. Right way to handle the exception is to probably stop the producer and start the producer from the last checkpoint. 

Please do send a pull request if you have a fix for this :). 

Thanks,
Srini.

**Comment by satyapraveen2002** [comment]
I came across the same issue, how to start from last checkpoint?
