### ISSUE TITLE
Does databus support AWS RDS?

### ISSUE THREAD

**Issue by steamymotel** [linkedin/databus#50]
Hi all,

Am Totally newbie on MySQL, I know there is limit on AWS RDS, just don't know the limitation is require by Databus.

**Comment by chavdar** [comment]
Sorry, I haven't used RDS. Does it provide access to the binlog?

**Comment by steamymotel** [comment]
Thanks for the reply. I am new to MySQL. The support maybe limited.

From RDS with MySQL 5.6
http://aws.amazon.com/about-aws/whats-new/2013/07/01/amazon-rds-mysql-5-6/

That it allow to access binlog via mysqlbinlog 

mysqlbinlog --read-from-remote-server --host=MySQL56Instance1.cg034hpkmmjt.region.rds.amazonaws.com --port=3306  --user ReplUser --password --raw --result-file=/tmp/ binlog.00098

Thanks

**Comment by psrinivasulu** [comment]
Hi @steamymotel, This would be an interesting experiement. We should theoretically work fine, If RDS supports mysql wire protocol. Please do let us know how the experiment went :). 

Thanks,
Srini.
