### ISSUE TITLE
Not able to connect to the DB for example project.

### ISSUE THREAD

**Issue by arjun1401** [linkedin/databus#52]
Hello,

I have updated the sources-person.json with my DB details but from the logs I can see that it is not able to find the table although all the tables/views/procedures required for databusification are created in DB including table Person. PFB the error snippet:

015-02-22 20:07:03,823 +3371 [EventProducerThread_person] (INFO) {person} JDBC Version is: 11.2.0.2.0
2015-02-22 20:07:06,437 +5985 [EventProducerThread_person] (ERROR) {OracleEventProducer_person} DatabusException occurred while reading events from person. This error may be due to a transient issue (database is down?):java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

com.linkedin.databus2.core.DatabusException: java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

Help on this will be highly appreciated. Thanks.

**Comment by chavdar** [comment]
Try enabling debug logging. That should tell you which table is missing.

**Comment by arjun1401** [comment]
Yes I am able to connect to DB now and able to execute the sample project. Since a week I am trying to figure out how to configure multiple producers OR multiple relays for a given table in order to get low latency time while reading the events from the consumer, but still no luck. Request you to kindly provide the resolution for the same.

One more concern, still unable to configure the project on Eclipse/IntelliJIDEA. For ex. in the PersonRelayServer.java, Cli is used but i couldnt find any import related to this in the class file. 

It will be great if some help is provided in order to setup the example project on eclipse or any other appropriate IDE.

**Comment by psrinivasulu** [comment]
Hi @arjun1401,

Please let us know if you still need help in this issue. 

Thanks,
Srini.
