### ISSUE TITLE
Is there any milestone to open source databus v3?

### ISSUE THREAD

**Issue by yanky80** [linkedin/databus#54]
I have noticed that Linkedin have been using databus v3 at internal usage in an introduction article of expresso databus. And databus v2 code has been stalled for a while. So I'm curious what features has been developed in v3? and when will the v3 be open sourced? Thanks for good work.

**Comment by psrinivasulu** [comment]
Hello @yanky80,

Currently there is no plan to open source the databusV3 since it is espresso specific and espresso is not open source yet. 

Thanks,
Srini.
