### ISSUE TITLE
How to transfer changes  from oracle to redis

### ISSUE THREAD

**Issue by yester354** [linkedin/databus#62]
Hello
          I am trying to synchronize data from oracle to redis .Now according to the wiki of databus.i succeed to get the change from oracle.but i dont know how to transfer the change data to a new database，for example redis.can you give me a example. thanks

**Comment by psrinivasulu** [comment]
Hi there,

Databus is a change capture system. It provides with the change events from the databases. Writing it to the destination system is client's responsibility. 

If you don't mind, Can you provide more details about yourself and how you are using databus for?

Thanks,
Srini.

**Comment by yester354** [comment]
Hi 
    I am a oracle dba and i am looking for a tool to synchronize data from oracle to other system.and i am interested in databus .now I want to use databus to archive my idea. but i dont know how to do it

**Comment by psrinivasulu** [comment]
You need to write a databus client to receive the change stream from datastream and write it to redis. You can find the sample client here https://github.com/linkedin/databus#example-client.

**Comment by darionyaphet** [comment]
hi  @psrinivasulu I'm working for MySQL binlog transfer to Apache Kafka . 
Could write a databus client for that ?

**Comment by yester354** [comment]
thanks @psrinivasulu  ,I will try .

**Comment by psrinivasulu** [comment]
Hi @darionyaphet Yes, You can write databus client to read the changes events from Mysql write to kafka.  You can find the details here on how to use databus for Mysql https://github.com/linkedin/databus/wiki/Databus-for-MySQL.

**Comment by darionyaphet** [comment]
@psrinivasulu  thanks .
